### ISSUE TITLE
Updating just one value of InstalledProduct

### ISSUE THREAD

**Issue by Egahras** [opendns/autotask-php#40] opened 2016-04-13 09:26 UTC
Is it possible to update just one value of an entity?

Ive got hundreds of installed Products, and now we need to update each InstalledProduct. But just one value.

I cant figure out if it is possible to say:

```
Update WarrantyExpirationDate => '2017-10-30'
for Installed Priduct id=664
```

if i make a new InstalledProduct object and just set the required fields and the value i want to get updated i loose all the other setted values which are not required...
Do i realy have to fetch each product and set all given values in a new object which ill use to update?
 As i mentioned in an issue last year, its not possible to just query the object and use the response as the "new Object" for updating...

We're building a huge synchronisation with our local system. If its the only choice to "recreate" the full object for updating an existing object, i wonder how much work ill have in... 4-6 month with updateing the synchronisation part cause someone added a userdefinedfield...

**Comment by reynolek** [comment] 2016-04-13 16:36
I believe updates in Autotask are patch requests (I wouldn't quote me on it, i'd test it first).

So in that manner, if you pull down each InstalledProduct, create a new InstalledProduct instance, set the new instance's ID to be the fetched InstalledProduct's ID, an then change the WarrantyExpirationDate to the new value, and submit that object as an update, it should only modify the 1 field.

This looks like how we handle our integration for InstalledProducts

**Comment by Egahras** [comment] 2016-04-13 17:02
hey reynolek,
i tried this and i want to share my experience... maybe im just thinking the wrong way?

1. I pulled the installedProduct i wanted to change.
2. I created a new Object of installedProduct.
3. I used the id of the exisiting InstalledProduct to fill the id field in the new object.
4. I filled in the WarrentyExpirationDate.

if i push this new Object, just with id and warrenty... i get error, cause of missing required values.
So i filled in the required values. I pushed the Object and lost all Data i didnt set to the object.

Yeah it would be realy nice if python and php worked the same way... but they dont... 
On 21 Oct 2014 i posted the issue, that i cant just push an Object i received. That would be realy nice. You told me:

> Welcome to the world of PSA Apis -- they do not always return what they expect back

Maybe i just have to start with python now.... Cause in the Company i work for they cant just say "ok thats the way we want to work.." they always change some things like UserDefinedFields... nearly every month 4-5 changes... and nobody tells me... so it would be hard to recreate every object and check the value types like boolean or string in my older issue....

**Comment by reynolek** [comment] 2016-04-13 17:39
What happens if you do the following?
1. Pull down the installed product
2. Update that object with the new warranty value
3. Push the same object up in an update call

Have you confirmed that the date format you are sending is valid for AT? I vaguely remember there being some tricky requirements for dates (although I also had to integrate with Connectwise at the same time, so I may be mixing the two together)

**Comment by Egahras** [comment] 2016-04-13 17:52
i tried but i get an error...

`[updateResult] => ATWS\AutotaskObjects\ATWSResponse Object
        (
            [EntityResults] => ATWS\AutotaskObjects\ArrayOfEntity Object
                (
                    [Entity] => 
                )

            [EntityResultType] => installedproduct
            [EntityReturnInfoResults] => ATWS\AutotaskObjects\ArrayOfEntityReturnInfo Object
                (
                    [EntityReturnInfo] => 
                    [Fields] => 
                    [UserDefinedFields] => 
                )

            [Errors] => ATWS\AutotaskObjects\ArrayOfATWSError Object
                (
                    [ATWSError] => Array
                        (
                            [0] => ATWS\AutotaskObjects\ATWSError Object
                                (
                                    [Message] => Conversion from type 'Object' to type 'String' is not valid.
                                )

                            [1] => ATWS\AutotaskObjects\ATWSError Object
                                (
                                    [Message] => Error updating entity for record number [1].
                                )

                        )

                    [Fields] => 
                    [UserDefinedFields] => 
                )

            [ReturnCode] => -1
        )`

im inserting the warrenty date like

`$product_old->WarrantyExpirationDate = '2017-10-30T00:00:00';`
or
`$product_old->WarrantyExpirationDate = '2017-10-30';`

Just like you did in the TicketCreate example with the DueDatetime
https://github.com/opendns/autotask-php/blob/master/ticket_create_example.php

**Comment by reynolek** [comment] 2016-04-13 18:14
That error leads me to believe that it is returning something that it cant quite handle on an update.

Our integration uses nearly exclusively UDFs so I dont know much about some of the regular fields for InstalledProduct.

My bet is field is being returned as either an Object when it wants a String, or the opposite (the error message is pretty ambiguous in this sense in my opinion). I remember when I was doing a mass update to installed products, there was some code that I wrote that string casted one of the fields I believe...but it was so long ago that I dont think I have that script anymore :disappointed:

**Comment by Egahras** [comment] 2016-04-14 06:25
so i have to write a script thats runs through the returned Object and set al the "standard" fields to the type it wants them back...

I cant understand why its always confusing like this...

**Comment by Egahras** [comment] 2016-04-14 12:44
I Found the reason why i couldnt upload the fetched Object...

https://github.com/opendns/autotask-php/issues/1

> reynolek commented on 19 Sep 2014
So the issue appears to be the way PHP Soap handles empty strings. Rather than creating an XML element such as <LinkedInUrl></LinkedInUrl>, it creates <LinkedInUrl />. This is valid markup, but seems to trip up Autotask's API.
A quick and dirty hack would be:
foreach($contact as $key => $value) {
    if ($value === '') {
        $contact->$key = null;
    }
}
This doesnt catch everything -- some fields still produce the <tag /> type element. You can also do $client->__getLastRequest() and $client->__getLastResponse() to get the exact XML being sent back and forth. It can help debug issues like this.

I mean its no solution to just update a single value without fetching and pushing the whole Object, but it works now... I think this thread can be closed....

**Comment by reynolek** [comment] 2016-04-15 23:29
You cannot update multiple entries at the same time -- Autotask doesn't support batching.

Response times are pretty slow.

**Comment by sander271** [comment] 2016-04-16 16:45
Hi Egahras and Reynolek,

The Autotask web services API does actually support the updating of multiple entities. As per their documentation: _The Web Service API calls can update or create a maximum of 200 objects with one call. If you send more than 200 elements in your array, the call will fail and no changes will occur in Autotask._  

Now I am using C# for all of my Autotask integrations and so I know how to send the proper SOAP call that way but not in php. I assume Reynolek's wrapper is what creates the actual SOAP document and sends it. If that's the case then in the update and create calls you need to send an Array of type Entity that contains up to 200 Entity objects of the information you are trying to create or update.

As for Egahras's issue above about just updating a single value of an entity you can just query the entities you want, take the information returned from the query call change the value and send that same object back in the update call. 
The reason why information is lost if you create a new object and only fill in the id field and the field you want to change happens is explained in their documentation: _When you use the update() call, all entity fields are updated unless they are ReadOnly. On update(), if no value is provided for non- ReadOnly fields, those fields are cleared._

Also for the error you received above, the type of the WarrantyExperationDate field of the InstalledProduct Entity is of the type DateTime. I'm not sure if that helps since I don't know how your wrapper handles the data once a call is made.
 
I hope this helps.

**Comment by Egahras** [comment] 2016-04-16 17:00
Hey sander271,
thanks for your reply. I'll try to update multiple objects at once with youre information.

Yeah, Reynolek's wrapper creates the SOAP document... But that wrapper is not the problem. PHP is the problem. I dont know why but the values of an object i fetch via the query function got wrong types. So it was not possible to use the object to update the entity. After i set the correct types for these values, im able to use the Object for an update without getting errors.

**Comment by reynolek** [comment] 2016-04-16 20:18
Ah that makes sense about batch update. 

I would have to implement it in the client wrapper but it should be very straight forward. I'll see if I can add and test it soon. It's not particularly complex.

**Comment by Egahras** [comment] 2016-04-19 06:19
Would be realy nice if you could implement this.

**Comment by reynolek** [comment] 2016-04-21 20:04
I believe this is all that is needed to implement bulk update: https://github.com/opendns/autotask-php/pull/41

**Comment by Egahras** [comment] 2016-04-22 06:56
So I put all Objects in an array and use bulkUpdate instead of Update, correct? I'll try... =) thanks

**Comment by reynolek** [comment] 2016-04-22 16:14
I merged in the change this morning

**Comment by reynolek** [comment] 2016-04-22 16:27
Oh I should add -- however you are pulling in the code, you will need to update the code to the new tag i created a few minutes ago.

**Comment by reynolek** [comment] 2016-05-24 22:49
@Egahras any luck with bulk update?

**Comment by SirPoot-** [comment] 2017-01-18 20:44
@reynolek The bulkUpdate function worked for me. Thank you for added the feature!

I did need to unset the blank and bull key value's and the UserDefinedFields. 

```
foreach($Response as $key => $value) {
	if ($value === '' || $value === null) {
		unset($Response->$key);
	}
}
unset($Response->UserDefinedFields);
```

For an example, I used the array_slice to break up the array into 200 object length

```
$slicedArray1 = array_slice($queryResults, 0, 200, true);
$slicedArray2 = array_slice($queryResults, 201, 200, true);
$slicedArray3 = array_slice($queryResults, 401, 200, true);

$bulkUpdate1Response = $client->bulkUpdate($slicedArray1);
$bulkUpdate2Response = $client->bulkUpdate($slicedArray2);
$bulkUpdate3Response = $client->bulkUpdate($slicedArray3);
```

I hope this helps others.

Thank you again Eric!

**Comment by reynolek** [comment] 2017-01-18 20:59
Yeah I hate that autotask returns data that you cant immediately put back into the API, we have run into that ourselves at OpenDNS.

Going to close the issue.

**Closed by reynolek** 2017-01-18 20:59 UTC
