### ISSUE TITLE
Getting an error for this update.

### ISSUE THREAD

**Issue by jbalter** [opendns/autotask-php#81] opened 2017-08-09 20:15 UTC
Here is my code:

```
//look for this value
$lookvalue = 'test';
//Replace with this value
$replacevalue = 'YES';

// End Edit Region

//errors display
ini_set('display_startup_errors', 1);
ini_set('display_errors', 1);
error_reporting(-1);


//This script logs in and does a query for a value in the alert and replaces it.

require_once __DIR__ . '\src\autoload.php';



//Login to system
$authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
$opts = array('trace' => 1);
$client = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);

$authOpts = array(
    'login' => $username,
    'password' => $password,
    'trace' => 1,   // Allows us to debug by getting the XML requests sent
);
$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($wsdl, $authOpts);


//Query the system for accountAlerts

//this is the query
$query = new ATWS\AutotaskObjects\Query('AccountAlert');

$Alerttexttoreplace = new ATWS\AutotaskObjects\QueryField('AlertText');

$Alerttexttoreplace->addExpression('contains', $lookvalue);

$query->addField($Alerttexttoreplace);

//set limited aray
$result = $client->query($query);
$final = $result->queryResult->EntityResults->Entity;

//Replace value in array
foreach ($final as $entity) {
    $entity->AlertText = str_replace($lookvalue, $replacevalue, $entity->AlertText);
	$client->update($entity);
	unset($final->$entity);
};
```

Here is the error

```
Fatal error: Uncaught SoapFault exception: [soap:Client] System.Web.Services.Protocols.SoapException: Server was unable to read request. ---> System.InvalidOperationException: There is an error in XML document (2, 218). ---> System.InvalidOperationException: The specified type is abstract: name='Entity', namespace='http://autotask.net/ATWS/v1_5/', at <Entity xmlns='http://autotask.net/ATWS/v1_5/'>.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read2_Entity(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read183_update()
   at Microsoft.Xml.Serialization.GeneratedAssembly.ArrayOfObjectSerializer32.Deserialize(XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializa in C:\php\Projects\Autotask\PHPfromopenDNS\src\Client.php on line 257



```

Any help would be welcome.

**Comment by SirPoot-** [comment] 2017-08-10 15:00
Duplicate of #77

**Comment by SirPoot-** [comment] 2017-08-10 15:07
I will try to look into this today. Let's work on the original issue you created as there is a lot of good information other could use.

**Comment by SirPoot-** [comment] 2017-11-07 15:44
After learning from @reynolek, I always run my entity through the following code before I perform a $client->update(). It removed all of keys that are empty, single space or null.
```
foreach($entity as $key => $value) {
    if ($value === '' || $value === ' ' || $value === null) {
        unset($entity->$key);
    }
}
unset($entity->UserDefinedFields);
```
Can you give this a try?

**Closed** 2018-05-03 00:34 UTC
